using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
using System.Data;
using System.Reflection;
using System.IO;
using GUITestLibrary;
using System.Text;

namespace AutomatedGUITest
{
	
	public class GUITestScript : System.Windows.Forms.Form
	{
		//generated by planting the GUI controls
		private System.ComponentModel.IContainer components;
		private System.Windows.Forms.Timer tmrStopScript;
		private System.Windows.Forms.Timer tmrAutomatedTest;
		private System.Windows.Forms.Timer tmrRunScript; 
		private System.Windows.Forms.Timer tmrVerifyTest;

		//fields added
		private string guiTestDataStore;
		private string progDir;
		
		private Form AUT;
        private GUITestUtility.GUIInfoSerializable seqGUIUT;

		private string guiTestActionLib;
		private int clickNum;
		private ArrayList resultList;

		//default constructor
		public GUITestScript()
		{
			InitializeComponent();
		}

		//over loaded constructor
		public GUITestScript(string _testDataStore, string _progDir)
		{
			InitializeComponent();
			guiTestDataStore = _testDataStore;
			progDir = _progDir;
		}

		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			this.tmrAutomatedTest = new System.Windows.Forms.Timer(this.components);
			this.tmrRunScript = new System.Windows.Forms.Timer(this.components);
			this.tmrStopScript = new System.Windows.Forms.Timer(this.components);
			this.tmrVerifyTest = new System.Windows.Forms.Timer(this.components);
			// 
			// tmrAutomatedTest
			// 
			this.tmrAutomatedTest.Enabled = true;
			this.tmrAutomatedTest.Tick += new System.EventHandler(this.tmrAutomatedTest_Tick);
			// 
			// tmrRunScript
			// 
			this.tmrRunScript.Tick += new System.EventHandler(this.tmrRunScript_Tick);
			// 
			// tmrStopScript
			// 
			this.tmrStopScript.Tick += new System.EventHandler(this.tmrStopScript_Tick);
			// 
			// tmrVerifyTest
			// 
			this.tmrVerifyTest.Tick += new System.EventHandler(this.tmrVerifyTest_Tick);
			// 
			// GUITestScript
			// 
			this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
			this.ClientSize = new System.Drawing.Size(292, 154);
			this.Name = "GUITestScript";
			this.Text = "Form1";

		}
		#endregion
		
		
		private void tmrAutomatedTest_Tick(object sender, System.EventArgs e)
		{
			StartAUT();

			tmrAutomatedTest.Enabled = false;
			tmrRunScript.Enabled = true;
			resultList = new ArrayList();
		}
		
		private void StartAUT()
		{
			seqGUIUT = new GUITestUtility.GUIInfoSerializable();
			object obj = (object)seqGUIUT;
			GUITestUtility.DeSerializeInfo(guiTestDataStore, ref obj);
			seqGUIUT = (GUITestUtility.GUIInfoSerializable)obj;

			string AUTPath = seqGUIUT.AUTPath;
			string startupType = seqGUIUT.AUTStartupForm;

			if (AUT == null)
				AUT = (Form)GUITestUtility.StartAUT(AUTPath, startupType);

			int hwnd = (int)AUT.Handle;
			StringBuilder sbClsName = new StringBuilder(128);
			GUITestActions.GetClassName(hwnd, sbClsName, 128);
			string clsName = sbClsName.ToString();
			string winText = AUT.Text;
			string pText = "";
			GUITestActions.SynchronizeWindow(ref hwnd, ref winText, ref clsName, ref pText); 
		}

		private void tmrRunScript_Tick(object sender, System.EventArgs e)
		{
			RunsScript();
			tmrRunScript.Enabled = false;
		
		}

		private void RunsScript()
		{
			guiTestActionLib = Path.Combine(progDir, "GUITestActionLib.xml");

			GUITestUtility.GUIInfo guiUnit = (GUITestUtility.GUIInfo)seqGUIUT.GUIList[clickNum];
				
			string ctrlAction = GUITestUtility.GetAGUIAction(guiTestActionLib, guiUnit.GUIControlType);
			
			StringBuilder sb = new StringBuilder(10000);

			Control ctrlTested = (Control)GUITestUtility.VerifyField(AUT, guiUnit.GUIControlName);
			GUITestActions.GetWindowText((int)ctrlTested.Handle, sb, 10000);

			object[] paramArr = new object[4];
			paramArr[0] = 0;
			paramArr[1] = sb.ToString();
			paramArr[2] = guiUnit.GUIClassName;
			paramArr[3] = guiUnit.GUIParentText;
			
			Type guiTestLibType = new GUITestActions().GetType();
			object obj = Activator.CreateInstance(guiTestLibType);
			MethodInfo mi = guiTestLibType.GetMethod(ctrlAction);
				
			try
			{
				mi.Invoke(obj, paramArr);
			}
			catch (Exception ex)
			{
				MessageBox.Show(ex.Message);
			}

			if (clickNum < seqGUIUT.GUIList.Count)
			{
				clickNum++;
				tmrRunScript.Enabled = false;
				tmrStopScript.Enabled = true;
			}

		}

		private void tmrStopScript_Tick(object sender, System.EventArgs e)
		{
			GUITestUtility.GUIInfo guiUnit = (GUITestUtility.GUIInfo)seqGUIUT.GUIList[clickNum - 1];
			Control ctrlTested;
			ctrlTested = (Control)GUITestUtility.VerifyField(AUT, guiUnit.GUIControlName);
			resultList.Add(ctrlTested.Text);

			if (clickNum >= seqGUIUT.GUIList.Count)
			{
				tmrRunScript.Enabled = false;
				tmrStopScript.Enabled = false;
				tmrVerifyTest.Enabled = true;
				try
				{
					AUT.Dispose();
				}
				catch{}
			}
			else
			{
				tmrRunScript.Enabled = true;
				tmrStopScript.Enabled = false;
			}
			
		}

		private void tmrVerifyTest_Tick(object sender, System.EventArgs e)
		{
			tmrVerifyTest.Enabled = false;

			string resultDataStore = guiTestDataStore.Replace(".xml", "_result.xml");
			GUITestUtility.SerilizeInfo(resultDataStore, resultList);

			this.Dispose();
		}
	}
}
